### ISSUE TITLE
Not compiling on MSVC

### ISSUE THREAD

**Issue by yghdj** [iboB/mscharconv#2] opened 2022-07-13 11:23 UTC
Hi,

I've imported your library in my project because I have a need for cross-platform `<charconv>`. The library works fine with GCC on MacOS (built with iOS SDK 15.0).

However, on Windows, compilation errors occurs when trying to compile for x64 target architecture with MSVC compiler. The error occurs in `charconv.inl`, like this:

```
include\third_party\msstl\converted\charconv.inl(476,111): error C2664: 'uint32_t msstl::impl::_Bit_scan_reverse(const msstl::impl::_Big_integer_flt &) noexcept': cannot convert argument 1 from 'uint32_t' to 'const msstl::impl::_Big_integer_flt &'

include\third_party\msstl\converted\charconv.inl(476,111): message : Reason: cannot convert from 'uint32_t' to 'const msstl::impl::_Big_integer_flt'

include\third_party\msstl\converted\charconv.inl(476,111): message : No constructor could take the source type, or constructor overload resolution was ambiguous

include\third_party\msstl\converted\charconv.inl(439,31): message : see declaration of 'msstl::impl::_Bit_scan_reverse'

````

Here is the list of options used when compiling: (minus the build folder and output arguments)

```
/JMC /permissive- /GS /W3 /Zc:wchar_t /ZI /Gm- /Od /sdl /Zc:inline /fp:precise /D "_DEBUG" /D "_CONSOLE" /D "_CRT_SECURE_NO_WARNINGS" /D "_UNICODE" /D "UNICODE" /D "DEBUGLOG" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /std:c++17 /FC  /EHsc /nologo  /diagnostics:column 
```

I wonder why the function `_Bit_scan_reverse` would be used with an argument of type `uint32_t` ? Seems like it'd be more likely used on your custom structures.

Thanks in advance for replying (if you still maintain this of course :) )

**Comment by iboB** [comment] 2022-07-17 04:25
I cannot reproduce this. The tests build and execute fine with the command line args you provided.

Can you provide some code which causes this error? A minimal repro example perhaps?

Also, which version of MSVC are you using?

**Comment by iboB** [comment] 2022-09-24 19:13
Closing for lack of info

**Comment by iboB** [comment] 2022-11-03 11:09
I was just able to reproduce it

**Closed as completed** 2022-11-03 11:46 UTC
